version: "3.9"

services:

  segment:
    container_name: segment-service
    depends_on:
      wait-for-postgres:
        condition: service_completed_successfully
    build: .
    env_file: .env
    ports:
      - "8080:8080"


  wait-for-postgres:
    image: atkrad/wait4x
    command: postgresql 'postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable'

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - "5432:5432"
