version: "3.9"

services:

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "54320:5432"